### ISSUE TITLE
research-app: "tools" bar prevents access to hamburger menu

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-webgl-engine#107]
I realized that now that we've moved the toolbar to the top of the viewport, there's a UI issue. The toolbar is positioned with some nested divs like so:

```css
#tools {
  position: absolute;
  z-index: 10;
  top: 0.5rem;
  left: 50%;
 
  .tool-container {
    position: relative;
    left: -50%;
  }
}
```

On my Chrome, the outer `#tools` div ends up spanning the right half of the viewport, while the inner `.tool-container` div is nicely centered. But because the outer div has a high z-index, it covers up the hamburger menu on the right even though it is invisible over there.

To be honest I forget why I did the positioning this way. There are lots of ways to center things horizontally in CSS.

This problem might be solved simple by putting the `z-index` setting inside the `.tool-container` rather than the outer `#tools` but there might be a good reason that it was placed on the outside anyway.
